# A quick makefile to generate all the end result files for you!
# Inmake got a bit tedious...
# Assumes you've got all the dependencies though :/ 

TEMPLATES=partials/edit-submit-view._template partials/list-item._template partials/script._template
PACKAGE_FILES=index.css main.min.js index.html highlight.pack.js

all: index.html index.css main.min.js

clean:
	@echo cleaning up files generated by build...
	-rm -fv index.html index.css main.min.js intermediate.css package.zip

package.zip: $(PACKAGE_FILES)
	zip package.zip $(PACKAGE_FILES)

index.html: index.jade layout.jade $(TEMPLATES)
	@echo generating the index page...
	jade index.jade

index.css: intermediate.css
	@echo auto-prefixing the css...
	myth intermediate.css index.css

intermediate.css: index.scss
	@echo generating the css...
	sass index.scss intermediate.css --sourcemap=none

main.min.js: main.js
	uglifyjs -c -o main.min.js main.js

