# A quick makefile to generate all the end result files for you!
# Inmake got a bit tedious...
# Assumes you've got all the dependencies though :/ 


CLOSURE_COMPILER=closure-compiler
TEMPLATES=partials/edit-submit-view._template list-item._template script._template
PACKAGE_FILES=index.css main.min.js index.html highlight.pack.js

.PHONY: all

clean: 
	@echo cleaning up files generated by build...
	-rm -fv index.html index.css *.map main.min.js intermediate.css

package.tar.gz:
	tar cvzf package.tar.gz $(PACKAGE_FILES)

index.html:
	@echo generating the index page...
	jade index.jade

index.css: intermediate.css
	@echo auto-prefixing the css...
	myth intermediate.css index.css

intermediate.css:
	@echo generating the css...
	sass index.scss intermediate.css --sourcemap=none

main.min.js: main.js
	$(CLOSURE_COMPILER) --js main.js --js_output_file main.min.js

all: clean index.html index.css main.min.js
no-clean: index.html index.css main.min.js